### ISSUE TITLE
incorrect authentication is coming again and again while signin into docker in my Mac m1  I was not able to sign in I had changed my password but that doesn't work .

### ISSUE THREAD

**Issue by Akashkumar-CS** [docker/scan-cli-plugin#162]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker scan --version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mat007** [comment]
I don’t think this is related to the `scan` plugin, is it?
Can you open an issue on https://github.com/docker/for-mac instead?
